### ISSUE TITLE
Shadda-Fatha breaks cursive positioning

### ISSUE THREAD

**Issue by simoncozens** [BornaIz/markazitext#16]
It probably needs to be explicitly made a Mark glyph in the Glyph Info dialog.

```
$ shape variable_ttf/MarkaziText-VF.ttf ''ضَمَّة''
[uniFE94=5+802|shaddaFathaar=2+575|uniFEE4=2+1051|uni064E=0@477,376+0|uniFEBF=0+1390]
```
![shape](https://user-images.githubusercontent.com/106728/127866212-eae96778-999c-4b72-9ea4-906e27d25fa8.png)

**Comment by BornaIz** [comment]
Fixed! 
<img width="758" alt="Screenshot 2022-12-14 at 17 55 41" src="https://user-images.githubusercontent.com/11202157/207671720-26f5dcc3-3f5e-4152-9ad1-b1e695933b22.png">
