### ISSUE TITLE
 (؁ ،؀،ڭ، ۆ، ۇ، ۉ ،ە) درخواست نامه های جدید

### ISSUE THREAD

**Issue by IlyasTarpan** [BornaIz/markazitext#18]
سلام! از شما برای ساختن این فونت رایگان بسیار سپاسگزارم. این احتمالاً یک درخواست معمولی است، اما از شما می خواهم که علائمی مانند **ڭ ، ۆ ،ۇ ،ۉ ،ە، ؀** و **؁** را به مرکزی اضافه کنید. آنها برای نمایش زبان کریمتاتاری مورد نیاز هستند.

**Comment by IlyasTarpan** [comment]
The letter ڭ should look like ك, with three noqtaa on top. You may have to let go of the little ‏ک a little bit down so that the three noqtas aren't too high
![Снимок экрана (74)](https://user-images.githubusercontent.com/113206717/205496970-cf4610ff-2270-45a6-baf2-e949a0c40ed1.png)
![Снимок экрана (76)](https://user-images.githubusercontent.com/113206717/205496973-8824bd4d-ae8c-4760-a73a-968a5a26b0d1.png)
![Снимок экрана (77)](https://user-images.githubusercontent.com/113206717/205496979-32a01dcd-f68c-4b5c-97a8-9b8bde79b409.png)

The letter ە (U+06D5) looks exactly like the "regular ه (U+0647)" only it does not connect with the following letters, and stands for a vowel sound. The Persians use the "usual" ه for this, only putting after it the Zero Width Sign (U + 200C), which, by the way, is also not in Markazi, and it would be nice to add it:
![Снимок экрана (65)](https://user-images.githubusercontent.com/113206717/205497012-ecd5d4e1-f348-45c5-8fab-7a85d8b8d081.png)
![Снимок экрана (64)](https://user-images.githubusercontent.com/113206717/205497017-7317d574-010f-4909-a4dc-ff82a1be421f.png)
![Снимок экрана (63)](https://user-images.githubusercontent.com/113206717/205497020-34a64f48-213c-4e2b-95d0-b8cd975dc594.png)

The letters ۆ ،ۇ ،ۉ look like و, with extras on top. They should look something like this: 
![Снимок экрана (81)](https://user-images.githubusercontent.com/113206717/205497045-4db9b38a-aa5c-409d-9314-3734acd7c3a4.png)
Important note: the damma over ۇ (U+06C7) must be different from the "regular" damma - it must be bolder, and look like a comma, in order to be distinguishable

And the signs ؁ and ؀. It seems to me that the form in Noto Naskh is a good form. 


By the way, do you prefer to communicate in Persian or English?
                                                                                                در ضمن، شما ترجیح می دهید به زبان فارسی ارتباط برقرار کنید یا انگلیسی؟

**Comment by BornaIz** [comment]
I have added the required characters to support Crimean Tatar and the extra signs that you have requested for both Regular and Bold masters. 
<img width="453" alt="Screenshot 2022-12-14 at 17 26 01" src="https://user-images.githubusercontent.com/11202157/207665927-e7d39204-0d53-4175-b967-6dbab5811354.png">
<img width="423" alt="Screenshot 2022-12-14 at 17 26 12" src="https://user-images.githubusercontent.com/11202157/207665942-bb44af59-0bfe-4921-b6be-d213366733dd.png">

**Comment by IlyasTarpan** [comment]
خیلی ممنون!
thanks a lot!
