### ISSUE TITLE
Small body size?

### ISSUE THREAD

**Issue by davelab6** [BornaIz/markazitext#5]
Quick question... the Latin seems very small on the body compared to eg Merriweather... 

<img width="1117" alt="screen shot 2018-05-24 at 16 32 02" src="https://user-images.githubusercontent.com/261579/40859487-fcf7944a-65af-11e8-8f88-53c9cb4539cf.png">

Could you explain why this is? :)

**Comment by BornaIz** [comment]
Hi Dave,

Sorry for the late reply.
This is because UPM of Markazi Text (following Tim Holloway's Adobe Arabic
model) is 2048.


*-*
PhD Student
Department of Typography and Graphic Communication
University of Reading

**Comment by davelab6** [comment]
But isn't the typeface drawn with that in mind? Or was it drawn on a 1000
UPM?

**Comment by BornaIz** [comment]
That allows generous line spacing which is required for fully vocalised Arabic text. For us that was a priority.

**Comment by davelab6** [comment]
Hmm. I took a look in comparison to all other Arabic families and Merriweather:

![named](https://user-images.githubusercontent.com/261579/41063510-d9ed63b2-69a6-11e8-8c3b-914d0b3f38a3.png)

Here's the cap height, x height, and some Arabic text, in the same order:

![arabic](https://user-images.githubusercontent.com/261579/41063509-d9dec0f0-69a6-11e8-87c8-eba74a8a427d.png)

This is still pretty small, and I think today you don't need to scale the type down so small to avoid clipping (due to the OS/2 table fsSelection "use typo metrics" flag - @m4rc1e is this explained better anywhere?)

**Comment by davelab6** [comment]
Bottom line, I'm going to accept and push this as-is, but I think it isn't quite right.

**Comment by IlyasTarpan** [comment]
> В итоге, я собираюсь принять и продвигать это как есть, но я думаю, что это не совсем правильно.

It's just a joke that other fonts adjust Arabic letters to Latin, and Markazi, on the contrary, Latin to Arabic, which I think is correct. Many type designers simply make large Latin letters as tall as possible (А,К,В), and make Arabic letters much smaller to allow for dicritics. And as a result, the Arabic text in the mass of Latin (Cyrillic, Greek alphabet) seems small. If you have used any phone where Noto Naskh Arabic is installed as a system font (for example, Samsung), then you probably know what I'm talking about. It doesn't look very good.
