### ISSUE TITLE
Seeing overlaps on Firefox

### ISSUE THREAD

**Issue by pathumego** [BornaIz/markazitext#7]
On macOS, Firefox: 60.0.2 (64-bit) 

<img width="888" alt="screen shot 2018-06-25 at 8 43 14 pm" src="https://user-images.githubusercontent.com/6846609/41858864-7da2c9b4-78b8-11e8-91d2-90c28f032184.png">

**Comment by badcat** [comment]
@pathumego Which version of macOS?  :)

**Comment by m4rc1e** [comment]
Same as #6

**Comment by pathumego** [comment]
On Sierra `10.12.6 (16G1408)` Closing in fav of #6
